import type { COI } from "../types/coi.types";

export const initialCOIData: COI[] = [
  {
    id: "1",
    property: "Maplewood Shopping Center",
    tenantName: "Johnson & Sons",
    tenantEmail: "johnson@example.com",
    unit: "101",
    coiName: "Tenant_CedarHei...",
    expiryDate: "2026-11-17",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-15T10:00:00Z"
  },
  {
    id: "2",
    property: "Oak Tree Tower",
    tenantName: "Smith Enterprises",
    tenantEmail: "smith@example.com",
    unit: "Suite 300",
    coiName: "GlobalMart_Insura...",
    expiryDate: "2025-11-20",
    status: "Expired",
    reminderStatus: "Sent (30d)",
    createdAt: "2024-12-10T10:00:00Z"
  },
  {
    id: "3",
    property: "Meadowbrook Plaza",
    tenantName: "Global Solutions",
    tenantEmail: "global@example.com",
    unit: "B-12",
    coiName: "UrbanOutfitters_C...",
    expiryDate: "2027-11-19",
    status: "Rejected",
    reminderStatus: "N/A",
    createdAt: "2025-01-20T10:00:00Z"
  },
  {
    id: "4",
    property: "Pine Hill Shopping Center",
    tenantName: "Patel Industries",
    tenantEmail: "patel@example.com",
    unit: "402",
    coiName: "TechInnovators_C...",
    expiryDate: "2026-03-15",
    status: "Expiring Soon",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-01T10:00:00Z"
  },
  {
    id: "5",
    property: "Huron Heights",
    tenantName: "Green Thumb Landscaping",
    tenantEmail: "greenthumb@example.com",
    unit: "Kiosk 3",
    coiName: "GreenEarth_COI_...",
    expiryDate: "2025-11-22",
    status: "Expiring Soon",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-05T10:00:00Z"
  },
  {
    id: "6",
    property: "Riverside Retail",
    tenantName: "Oceanfront Realty",
    tenantEmail: "oceanfront@example.com",
    unit: "Unit 1",
    coiName: "EcoLiving_COI_E...",
    expiryDate: "2027-11-21",
    status: "Expiring Soon",
    reminderStatus: "Sent (30d)",
    createdAt: "2024-11-15T10:00:00Z"
  },
  {
    id: "7",
    property: "Maplewood Shopping Center",
    tenantName: "Apex Consulting",
    tenantEmail: "apex@example.com",
    unit: "Warehouse Unit A",
    coiName: "UrbanOutfitters_C...",
    expiryDate: "2028-11-18",
    status: "Not Processed",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-10T10:00:00Z"
  },
  {
    id: "8",
    property: "Windy Ridge Mall",
    tenantName: "Stark Industries",
    tenantEmail: "stark@example.com",
    unit: "Penthouse",
    coiName: "FutureTrends_COI...",
    expiryDate: "2026-11-24",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-25T10:00:00Z"
  },
  {
    id: "9",
    property: "Cedar Grove Complex",
    tenantName: "Wayne Enterprises",
    tenantEmail: "wayne@example.com",
    unit: "210",
    coiName: "HealthFirst_COI_...",
    expiryDate: "2028-11-17",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-30T10:00:00Z"
  },
  {
    id: "10",
    property: "Cedar Grove Complex",
    tenantName: "Wayne Enterprises",
    tenantEmail: "wayne@example.com",
    unit: "210",
    coiName: "HealthFirst_COI_...",
    expiryDate: "2028-11-17",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-30T10:00:00Z"
  },
  {
    id: "11",
    property: "Sunset Boulevard Plaza",
    tenantName: "Bright Foods Co.",
    tenantEmail: "brightfoods@example.com",
    unit: "105",
    coiName: "BrightFoods_COI...",
    expiryDate: "2026-08-12",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-05T10:00:00Z"
  },
  {
    id: "12",
    property: "Lakeside Business Park",
    tenantName: "Everest Traders",
    tenantEmail: "everest@example.com",
    unit: "Suite 220",
    coiName: "EverestTraders_C...",
    expiryDate: "2025-09-30",
    status: "Expired",
    reminderStatus: "Sent (30d)",
    createdAt: "2024-10-15T10:00:00Z"
  },
  {
    id: "13",
    property: "Downtown Commerce Hub",
    tenantName: "Nova Tech Systems",
    tenantEmail: "nova@example.com",
    unit: "301",
    coiName: "NovaTech_COI...",
    expiryDate: "2027-04-18",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-18T10:00:00Z"
  },
  {
    id: "14",
    property: "Silver Oak Center",
    tenantName: "Blue Sky Clothing",
    tenantEmail: "bluesky@example.com",
    unit: "Unit 9",
    coiName: "BlueSkyApparel_C...",
    expiryDate: "2026-02-10",
    status: "Expiring Soon",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-08T10:00:00Z"
  },
  {
    id: "15",
    property: "Hilltop Market Square",
    tenantName: "Prime Fitness Club",
    tenantEmail: "primefit@example.com",
    unit: "Gym Floor",
    coiName: "PrimeFitness_COI...",
    expiryDate: "2025-12-05",
    status: "Expiring Soon",
    reminderStatus: "Sent (60d)",
    createdAt: "2024-12-20T10:00:00Z"
  },
  {
    id: "16",
    property: "Crescent Bay Mall",
    tenantName: "Starline Jewelry",
    tenantEmail: "starline@example.com",
    unit: "Kiosk 7",
    coiName: "Starline_COI...",
    expiryDate: "2027-10-22",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-12T10:00:00Z"
  },
  {
    id: "17",
    property: "Brookfield Shopping Arcade",
    tenantName: "Zen Spa Retreat",
    tenantEmail: "zenspa@example.com",
    unit: "Suite 15",
    coiName: "ZenSpa_COI...",
    expiryDate: "2025-11-14",
    status: "Expired",
    reminderStatus: "Sent (30d)",
    createdAt: "2024-09-12T10:00:00Z"
  },
  {
    id: "18",
    property: "Harborfront Plaza",
    tenantName: "Golden Harvest Grocers",
    tenantEmail: "goldenharvest@example.com",
    unit: "102",
    coiName: "GoldenHarvest_C...",
    expiryDate: "2026-06-19",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-02T10:00:00Z"
  },
  {
    id: "19",
    property: "Evergreen Corporate Tower",
    tenantName: "Summit Law Group",
    tenantEmail: "summitlaw@example.com",
    unit: "Suite 900",
    coiName: "SummitLaw_COI...",
    expiryDate: "2026-01-25",
    status: "Rejected",
    reminderStatus: "N/A",
    createdAt: "2025-01-28T10:00:00Z"
  },
  {
    id: "20",
    property: "Westgate Retail Park",
    tenantName: "Urban Coffee House",
    tenantEmail: "urbancoffee@example.com",
    unit: "Cafe 4",
    coiName: "UrbanCoffee_COI...",
    expiryDate: "2027-09-01",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-01-22T10:00:00Z"
  },

  {
    id: "21",
    property: "Grand Central Complex",
    tenantName: "Metro Electronics",
    tenantEmail: "metroelec@example.com",
    unit: "Unit 18",
    coiName: "MetroElectronics...",
    expiryDate: "2025-10-05",
    status: "Expiring Soon",
    reminderStatus: "Sent (30d)",
    createdAt: "2024-12-01T10:00:00Z"
  },
  {
    id: "22",
    property: "Palm Grove Plaza",
    tenantName: "Happy Kids Daycare",
    tenantEmail: "happykids@example.com",
    unit: "Suite 2A",
    coiName: "HappyKids_COI...",
    expiryDate: "2026-12-12",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-11T10:00:00Z"
  },
  {
    id: "23",
    property: "Canyon Ridge Mall",
    tenantName: "Elite Travel Agency",
    tenantEmail: "elitetravel@example.com",
    unit: "Suite 505",
    coiName: "EliteTravel_COI...",
    expiryDate: "2025-07-19",
    status: "Expired",
    reminderStatus: "Sent (90d)",
    createdAt: "2024-08-20T10:00:00Z"
  },
  {
    id: "24",
    property: "Summit Point Center",
    tenantName: "Green Valley Pharmacy",
    tenantEmail: "greenvalley@example.com",
    unit: "Unit 6",
    coiName: "GreenValley_COI...",
    expiryDate: "2027-03-30",
    status: "Active",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-03T10:00:00Z"
  },
  {
    id: "25",
    property: "Redwood Business Hub",
    tenantName: "Pixel Design Studio",
    tenantEmail: "pixelstudio@example.com",
    unit: "Suite 401",
    coiName: "PixelStudio_COI...",
    expiryDate: "2026-05-14",
    status: "Not Processed",
    reminderStatus: "Not Sent",
    createdAt: "2025-02-14T10:00:00Z"
  }
];